# Generated by Django 4.2.7 on 2023-12-10 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secure_motor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='firstname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='lastname',
            new_name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
