# Generated by Django 4.2.7 on 2023-12-27 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secure_motor', '0002_rename_firstname_client_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
