# Generated by Django 4.2.7 on 2024-01-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_motor', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
